#pragma once

enum WeaponModelType_t
{
	WEAPONMODEL_UNRECOGNIZED = 0x0,
	WEAPONMODEL_VIEWMODEL = 0x1,
	WEAPONMODEL_DROPPEDMODEL = 0x2,
	WEAPONMODEL_UNCLASSIFIED = 0x4,
};

enum WeaponMode_t
{
	WEAPONMODE_SECONDARY = 0x1,
};

enum WeaponType_t
{
	WEAPONTYPE_KNIFE = 0x0,
	WEAPONTYPE_PISTOL = 0x1,
	WEAPONTYPE_SUBMACHINEGUN = 0x2,
	WEAPONTYPE_RIFLE = 0x3,
	WEAPONTYPE_SHOTGUN = 0x4,
	WEAPONTYPE_MACHINEGUN = 0x5,
	WEAPONTYPE_C4 = 0x6,
	WEAPONTYPE_GRENADE = 0x7,
	WEAPONTYPE_STACKABLEITEM = 0x8,
};

// Ref: server.dll 0F 47 C8 80 7C 24 22 00
#define KNIFE_MAX_DOT_FOR_BACKSTAB 0.475f

// Ref: server.dll F3 0F 59 1D ? ? ? ? F3 0F 5C E1
#define GRENADE_SECONDARY_TRANSITION 1.3f
// Ref: 
#define GRENADE_FAILSAFE_MAX_BOUNCES 20