#pragma once

enum TryCastVoteResult_t
{
	VOTE_CAST_OK = 0x0,
	VOTE_CAST_FAIL_SERVER_DISABLE = 0x1,
	VOTE_CAST_FAIL_NO_ACTIVE_ISSUE = 0x2,
	VOTE_CAST_FAIL_TEAM_RESTRICTED = 0x3,
	VOTE_CAST_FAIL_NO_CHANGES = 0x4,
	VOTE_CAST_FAIL_DUPLICATE = 0x5,
	VOTE_CAST_FAIL_VOTE_CLOSED = 0x6,
	VOTE_CAST_FAIL_SYSTEM_ERROR = 0x7,
};
